// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $HaveQuestionsIsland from "./islands/HaveQuestionsIsland.tsx";
import * as $ReferAndEarnPageBannerIsland from "./islands/ReferAndEarnPageBannerIsland.tsx";
import * as $RegulationTextIsland from "./islands/RegulationTextIsland.tsx";
import * as $WhoIndicatesIsland from "./islands/WhoIndicatesIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
  },
  islands: {
    "./islands/HaveQuestionsIsland.tsx": $HaveQuestionsIsland,
    "./islands/ReferAndEarnPageBannerIsland.tsx": $ReferAndEarnPageBannerIsland,
    "./islands/RegulationTextIsland.tsx": $RegulationTextIsland,
    "./islands/WhoIndicatesIsland.tsx": $WhoIndicatesIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
